In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv("data/imdb_processed.csv")

In [4]:
df.head()

,Keywords,belongs_to_collection,cast,crew,genres,original_language,original_title,overview,production_companies,production_countries,...,year,month,day,weekofday,quarter,budget,popularity,runtime_h,runtime_m,revenue
0,time travel;sequel;hot tub;duringcreditsstinger;,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",Rob Corddry;Craig Robinson;Clark Duke;Adam Sco...,"[{'credit_id': '59ac067c92514107af02c8c8', 'de...",Comedy;,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",Paramount Pictures;United Artists;Metro-Goldwy...,US;,...,2015.0,2.0,20.0,4.0,1.0,16.454568,2.024905,1.0,33.0,12314651.0
1,coronation;duty;marriage;falling in love;,"[{'id': 107674, 'name': 'The Princess Diaries ...",Anne Hathaway;Julie Andrews;H√©ctor Elizondo;J...,"[{'credit_id': '52fe43fe9251416c7502563d', 'de...",Comedy;Drama;Family;Romance;,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,Walt Disney Pictures;,US;,...,2004.0,8.0,6.0,4.0,3.0,17.504390,2.224504,1.0,53.0,95149435.0
2,jazz;obsession;conservatory;music teacher;new ...,NaN,Miles Teller;J.K. Simmons;Melissa Benoist;Aust...,"[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",Drama;,en,Whiplash,"Under the direction of a ruthless instructor, ...",Bold Films;Blumhouse Productions;Right of Way ...,US;,...,2014.0,10.0,10.0,4.0,4.0,15.009433,4.178992,1.0,45.0,13092000.0
3,mystery;bollywood;police corruption;crime;indi...,NaN,Vidya Balan;Nawazuddin Siddiqui;Parambrata Cha...,"[{'credit_id': '52fe48779251416c9108d6eb', 'de...",Thriller;Drama;,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,NaN,IN;,...,2012.0,3.0,9.0,4.0,1.0,13.997833,1.429099,2.0,2.0,16000000.0
4,NaN,NaN,Kim Kang-woo;Jo Jae-hyeon;Park Si-yeon;Kim Joo...,"[{'credit_id': '52fe464b9251416c75073b43', 'de...",Action;Thriller;,ko,마린보이,Marine Boy is the story of a former national s...,NaN,KR;,...,2009.0,2.0,5.0,3.0,1.0,0.000000,0.764570,1.0,58.0,3923970.0